### ISSUE TITLE
Haskell code similar to objects.cpp or structs.rs

### ISSUE THREAD

**Issue by yegor256** [yegor256/fibonacci#12]
Would be great to have `haskell/objects.hs` file, where the algorithm would be implemented in a similar way to what we do in `cpp/objects.cpp` and `rust/structs.rs`.

**Comment by yegor256** [comment]
@kostochkin can you do this please?

**Comment by kostochkin** [comment]
@yegor256  I created a pull request: https://github.com/yegor256/fibonacci/pull/14
There are several implementations. Similar to `rust` and `c++` can be found in `haskell/polymorphic_recursion.hs` and `haskell/object.hs + haskell/Mainlib/objects.hs` correspondingly

**Comment by yegor256** [comment]
@kostochkin thanks!
