### ISSUE TITLE
```functions.cpp``` and ```objects.cpp``` are not as similar as they can

### ISSUE THREAD

**Issue by MCJOHN974** [yegor256/fibonacci#18]
In  ```functions.cpp``` solution we don't wrap ```if``` into the function, but in ```objects.cpp``` we do. So, this solutions are not as similar as they can be, I think we should fix it.

**Comment by yegor256** [comment]
@MCJOHN974 let's add function `iff`

**Comment by MCJOHN974** [comment]
@yegor256 there are some issues with infinitive recursion in ```iff``` function. Maybe we should merge #19 ? I think now calculations in ```If```  object takes a significant time, but ```functions.cpp``` have no analogue to this calculations

**Comment by yegor256** [comment]
@MCJOHN974 I agree. Let's do what you suggested.
