### ISSUE TITLE
Add link to benchmark in README

### ISSUE THREAD

**Issue by MCJOHN974** [yegor256/fibonacci#37]
@yegor256 can we add some information about how we get information for https://yegor256.github.io/fibonacci/index.html ?

**Comment by yegor256** [comment]
@MCJOHN974 what do you mean? what is "some information"?

**Comment by MCJOHN974** [comment]
@yegor256 if code that collected information is open source -- link to repository. If we used some not open source tools -- names of this tools or links to websites of this tools

**Comment by yegor256** [comment]
@yegor256 there is a link to this repository in the page, at the bottom

**Comment by MCJOHN974** [comment]
@yegor256 I mean not the code of programs, which performance we are measuring. I mean tools that count assembly instructions and time

**Comment by yegor256** [comment]
@MCJOHN974 we use "perf". The HTML reports explicits mentions it.
