### ISSUE TITLE
Make bug

### ISSUE THREAD

**Issue by MCJOHN974** [yegor256/fibonacci#4]
If i run ```make sa```, then run ```make```,

```make``` shows an error:
```
In file included from src/recursion.cpp:21:
src/../include/main.h:32:31: error: expected expression
    for (int i = 0; i < CYCLES; ++i) {
                              ^
1 error generated.
make: *** [Makefile:67: asm/recursion.asm] Error 1

                              
```
                              
                              
I think it is a mistake in ```Makefile```, but i dont know exactly

**Comment by yegor256** [comment]
@MCJOHN974 it's fixed, try again. But this time, start with `make clean`.
