### ISSUE TITLE
src/decorators.cpp memory leak?

### ISSUE THREAD

**Issue by kostochkin** [yegor256/fibonacci#6]
It seems that `src/decorators.cpp` has a memory leak. 
Run `make FACTOR=1000`, then run `top`. Memory consumption will be constantly growing when decorators.bin is running.

**Comment by yegor256** [comment]
@kostochkin I believe I fixed that already. Can you check again and confirm you still have the issue?

**Comment by kostochkin** [comment]
Yes, the growing still exists in my environment.

I used this command for logging memory consuption:
```
top -d 1 -b | grep --line-buffered decorators | tee toplog.txt
```
And ran `make FACTOR=1000` on the newly cloned repository.

Here is my [toplog.txt](https://github.com/yegor256/fibonacci/files/7876906/toplog.txt) file.

**Comment by yegor256** [comment]
@kostochkin do you know a method of checking for memory leaks automatically? We would add it to the `Makefile`, to avoid such problems in the future.

**Comment by kostochkin** [comment]
@yegor256 I have just found a solution. Clang provides a flag [-fsanitize=leak](https://clang.llvm.org/docs/LeakSanitizer.html). I tried it, it seems working and give an useful output.

**Comment by yegor256** [comment]
@kostochkin tested and fixed, thanks for your help!
